lsi: false
host: mperry.github.com
url: http://mperry.github.com
title.full: Software Matters!: Thoughts on the discipline of Software Engineering
title.short: Software Matters
email: maperry78@yahoo.com.au
name: Mark Perry

